server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # 修复 .mjs 文件的 MIME 类型问题
  include /etc/nginx/mime.types;
  types {
    application/javascript mjs;
  }

  location = /runtime-config.js {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    expires -1;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
